add stat
aleshchenko37/java-explore-with-me pull request #2
Opened 2023-12-12 20:29 UTC by aleshchenko37

2023-12-13 08:19 UTC, VadimZharkov commented on stats/pom.xml
> +        <dependency>
в родительском помнике  <dependencies> лучше убрать, даже если он общий для всех дочерних (такие рекомендации по дипл проекту)

2023-12-13 08:21 UTC, VadimZharkov commented on stats/stats-client/src/main/java/ru/practicum/ewm/StatsClient.java
> +            final HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
статус ответа нужно обрабатывать (в эксепшн все кроме 200т го)

2023-12-13 08:24 UTC, VadimZharkov commented on stats/stats-client/src/main/java/ru/practicum/ewm/StatsClient.java
> +        } catch (NullPointerException | IOException | InterruptedException e) {
NullPointerException это особое исключение, говорит о том что разработчик передал null туда где ожидается не null. Т.е. это косяк разработчика. Поэтому его никогда не перехватывают, а на этапе тестирования добиваются чтобы оно не возникало в принципе путем понимания где оно возникло и исправления этой ситуации.

2023-12-13 08:30 UTC, VadimZharkov commented on stats/stats-dto/pom.xml
> +            <version>1.18.20</version>
Версии зависимостей в зависимостях нужно стараться избегать или вынести их в свойства самого родительского помника

2023-12-13 08:31 UTC, VadimZharkov commented on stats/stats-dto/pom.xml
> +            <groupId>com.fasterxml.jackson.core</groupId>
Возможно лишняя зависимость, посмотри может она уже присутствует в spring-boot-starter-validation

2023-12-13 08:32 UTC, VadimZharkov commented on stats/stats-server/pom.xml
> +            <version>1.6.0.Beta1</version>
Постарайся версию убрать или вынести в свойства родительского

2023-12-13 08:33 UTC, VadimZharkov commented on stats/stats-server/pom.xml
> +            <version>1.18.20</version>
Постарайся версию убрать или вынести в свойства родительского

2023-12-13 08:35 UTC, VadimZharkov commented on stats/stats-server/pom.xml
> +            <groupId>org.mapstruct</groupId>
Вижу мапперы сделагны руками, тогда зачем mapstruct?

2023-12-13 08:36 UTC, VadimZharkov requested changes
Можно улучшить

2023-12-13 08:57 UTC, aleshchenko37 commented on stats/stats-server/pom.xml
> +            <groupId>org.mapstruct</groupId>
Да, изначально хотела через @Mapper сделать, но не получилось(

2023-12-13 09:34 UTC, aleshchenko37 commented on stats/stats-dto/pom.xml
> +            <groupId>com.fasterxml.jackson.core</groupId>
Она не входит в spring-boot-starter-validation, пришлось оставить. В руководстве о @JsonFormat (https://www.baeldung.com/jackson-jsonformat) указана эта зависимость

2023-12-13 10:00 UTC, aleshchenko37 commented on stats/stats-client/src/main/java/ru/practicum/ewm/StatsClient.java
> +            final HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
Добавить ErrorHandler? Мы его разве не только в контроллеры добавляем?

2023-12-13 14:00 UTC, VadimZharkov commented on stats/stats-client/src/main/java/ru/practicum/ewm/StatsClient.java
> +            final HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
Нет не про ErrorHandler речь, можно и без эксепшена, но какя-то проверка на 200ый статус быть должна, например так
		if (HttpStatus.valueOf(response.statusCode()).is2xxSuccessful()) {
				return gson.fromJson(response.body(), EndpointHit.class);
		}

2023-12-13 14:02 UTC, VadimZharkov requested changes
Дрбавить проверку статуса

2023-12-14 07:05 UTC, VadimZharkov approved these changes

2023-12-14 14:07 UTC, merged