add main service
aleshchenko37/java-explore-with-me pull request #3
Opened 2023-12-26 20:03 UTC by aleshchenko37

2024-01-03 09:08 UTC, VadimZharkov commented on ewm-service/src/main/java/ru/practicum/ewm/category/controller/CategoryAdminController.java
> +    @Validated
А группа валидации не указана почему то?

2024-01-03 09:11 UTC, VadimZharkov commented on ewm-service/src/main/java/ru/practicum/ewm/category/controller/CategoryAdminController.java
> +    public ResponseEntity<CategoryDto> saveCategory(@Valid @RequestBody NewCategoryDto newCategoryDto) {
Лучше возвращать CategoryDto без ResponseEntity.
Статус нужный можно вернуть аннотацией @ResponseStatus(HttpStatus.CREATED) не метод

2024-01-03 09:15 UTC, VadimZharkov commented on ewm-service/src/main/java/ru/practicum/ewm/category/controller/CategoryController.java
> +            @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
Чтобы  `@PositiveOrZero `и подобные на параметрах сработали нужно на контроллер навесить `@Validated`

2024-01-03 09:23 UTC, VadimZharkov commented on ewm-service/src/main/java/ru/practicum/ewm/util/UtilService.java
> +public class UtilService {
Это класс определенно мне не нравится) 
Во первых утильные (Util префикс или суффикс) классы имеют обычно static методы и соответственно не имеют экземпляров.
Во вторый здесь явно нарушен single responsobility принцип. 
Для исправления ситуации можно просто в каждый сервис добавить по одному методу

2024-01-03 09:28 UTC, VadimZharkov requested changes
Можно улучшить

2024-01-03 12:07 UTC, aleshchenko37 commented on ewm-service/src/main/java/ru/practicum/ewm/util/UtilService.java
> +public class UtilService {
Перенесла методы в соответствующие сервисы, но модификаторы оставила public, т.к. private методы нельзя тестировать с помощью Mock. Можно ли оставить их публичными?

2024-01-03 12:50 UTC, aleshchenko37 commented on ewm-service/src/main/java/ru/practicum/ewm/category/controller/CategoryAdminController.java
> +    @Validated
На входе NewCategoryDto, содержит только одно поле, поэтому аннотации @NotBlank и @Size применяются в любом случае. CategoryDto - аналогично, только еще присваивается id.

2024-01-04 08:24 UTC, VadimZharkov approved these changes

2024-01-04 10:02 UTC, merged